### ISSUE TITLE
blocks inside inactive bridge maker disappear after joining again

### ISSUE THREAD

**Issue by Raviolibolonesa** [GeheimagentNr1/BridgeMaker#2]
### Minecraft Version

1.20.1

### Minecraft Forge Version

47.2.1

### Mod Version

2.0.2

### Describe the bug

everything inside the bridge maker disappears once you leave and enter the world

### Expected behavior

to fix the bug

### Steps to reproduce

1. fix the bug
2. we happy

**Comment by GeheimagentNr1** [comment]
<table><tbody><tr><th>Status:</th><td>Investigations running</td></tr><tr><th>Issue type:</th><td>Critical Bug</td></tr><tr><th>Fix type:</th><td>Bugfix</td></tr><tr><th>Fix version:</th><td>2.0.3</td></tr><tr><th>Fix release date:</th><td>05.12.2023</td></tr></tbody></table>

**Issue confirmed for:**

*   Minecraft version: 1.19.3  
    Forge version: 44.0.36  
    Mod version: 2.0.2
*   Minecraft version: 1.19.4  
    Forge version: 45.1.19  
    Mod version: 2.0.2
*   Minecraft version: 1.20  
    Forge version: 46.0.14  
    Mod version: 2.0.2
*   Minecraft version: 1.20.1  
    Forge version: 47.2.1  
    Mod version: 2.0.2
*   Minecraft version: 1.20.2  
    Forge version: 48.0.35  
    Mod version: 2.0.2

**TODOs:**

*   [x] Test Minecraft 1.18.2, Forge 40.2.10, Mod version 2.0.1, Mode Singleplayer
*   [x] Test Minecraft 1.19, Forge 41.1.0, Mod version 2.0.2, Mode Singleplayer
*   [x] Test Minecraft 1.19.2, Forge 43.2.23, Mod version 2.0.2, Mode Singleplayer
*   [x] Test Minecraft 1.19.3, Forge 44.0.36, Mod version 2.0.2, Mode Singleplayer
*   [x] Test Minecraft 1.19.4, Forge 45.1.19, Mod version 2.0.2, Mode Singleplayer
*   [x] Test Minecraft 1.20, Forge 46.0.14, Mod version 2.0.2, Mode Singleplayer
*   [x] Test Minecraft 1.20.1, Forge 47.2.1, Mod version 2.0.2, Mode Multiplayer + Singleplayer
*   [x] Test Minecraft 1.20.2, Forge 48.0.35, Mod version 2.0.2, Mode Singleplayer

**Comment by GeheimagentNr1** [comment]
Thank you for reporting this issue.  
I will fix it as soon as possible.

**Comment by GeheimagentNr1** [comment]
Issue is fixed with version 2.0.3, provided for Minecraft 1.19.3, 1.19.4, 1.20.1 and 1.20.2.
The fix will be not provided for Minecraft 1.20, because build for Minecraft 1.20 is with Forge currently not possible anymore.
